### ISSUE TITLE
Issue with __str__ of providers without locale

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#168]
So, now if we try this:

```python
from elizabeth import Numbers

n = Numbers()
print(n))
```

We will get this:

```
Traceback (most recent call last):
  File "/home/lk/Development/open_source/elizabeth/app.py", line 5, in <module>
    print(Numbers())
  File "/home/lk/Development/open_source/elizabeth/elizabeth/core/providers.py", line 79, in __str__
    locale_info(self.locale)
  File "/home/lk/Development/open_source/elizabeth/elizabeth/utils.py", line 30, in locale_info
    locale = locale.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Because not all providers need locale.

**Comment by lk-geimfari** [comment]
@sobolevn What do you propose to do? Maybe just don't inherit the `BaseProvider()` when providers does not need locale?

**Comment by sobolevn** [comment]
Maybe it is good idea to refactor `locale_info()` not to break on `None` values?
I am strongly sure that all providers must inherit from some base class.

**Comment by lk-geimfari** [comment]
@sobolevn Agree. I will refactor it.

**Comment by lk-geimfari** [comment]
@Valerievich And this.

**Comment by Valerievich** [comment]
This  issue is no longer relevant I think, right?

**Comment by lk-geimfari** [comment]
@Valerievich Actually is relevant. Check this out, please.

**Comment by Valerievich** [comment]
I've built mimesis from master and got this:
```(elizabeth_env) Ruslans-MacBook-Pro:mimesis ruslanv.$ python3
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mimesis import Numbers
>>> n = Numbers()
>>> print(n)
Numbers:en:English
```

**Comment by lk-geimfari** [comment]
@Valerievich Magic. I do not remember fixing this.

**Comment by lk-geimfari** [comment]
@Valerievich Anyway, it's cool.
