### ISSUE TITLE
Installation fails with Windows and Python 3.5.2 x64

### ISSUE THREAD

**Issue by mpibpc-mroose** [lk-geimfari/mimesis#228]
Hi,
if I try to `pip install mimesis` I get the following error:

```
Collecting mimesis
  Using cached mimesis-0.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mroose\AppData\Local\Temp\pycharm-packaging\mimesis\setup.py", line 10, in <module>
        with open('PYPI_README.rst', 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'PYPI_README.rst'
    
    ----------------------------------------
```
Seems to be some kind of bug?

Thanks,
Marco

**Comment by lk-geimfari** [comment]
@mpibpc-mroose Yeah, i'll fix it. Until, you can install it manually. Thanks for this report!

**Comment by lk-geimfari** [comment]
@mpibpc-mroose I have fixed this issue. Please, try now.

**Comment by lk-geimfari** [comment]
@mpibpc-mroose Can you confirm that bug was fixed?

**Comment by mpibpc-mroose** [comment]
It's fine now! Thanks for the fast response.
