### ISSUE TITLE
More informative messages for NonEnumerableError

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#293]
Now it's looks like that:

```python
>>> from mimesis import Cryptographic
>>> c = Cryptographic()
>>> c.hash(algorithm='nil')
```

Output:
```
Traceback (most recent call last):
  File "/home/user/Development/open_source/mimesis/.test.py", line 8, in <module>
    print(c.hash(algorithm='nil'))
  File "/home/user/Development/open_source/mimesis/mimesis/providers/cryptographic.py", line 41, in hash
    raise NonEnumerableError('Algorithm')
mimesis.exceptions.NonEnumerableError: You should use item of enum object «Algorithm» 
from module mimesis.enums
```

Any ideas?

**Comment by sobolevn** [comment]
Maybe list possible value?
