### ISSUE TITLE
Issue on installing using pip

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#304]
```
(mi) ➜  ~  pip install mimesis 
Collecting mimesis
  Downloading mimesis-1.0.0.tar.gz (2.5MB)
    100% |████████████████████████████████| 2.5MB 447kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3f7c6gq4/mimesis/setup.py", line 17, in <module>
        with open('dev_requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'dev_requirements.txt'
```

**Comment by lk-geimfari** [comment]
An exception here:

```python
with open('dev_requirements.txt') as f:
    tests_requirements = f.read().splitlines()
```
I think that it's can be easily fixed like that:
```python
try:
    with open('dev_requirements.txt') as f:
        tests_requirements = f.read().splitlines()
except FileNotFoundError:
    tests_requirements = []
```
