### ISSUE TITLE
Choice returns UnsupportedField when used with Field

### ISSUE THREAD

**Issue by cryocaustik** [lk-geimfari/mimesis#619]
# Bug report

## What's wrong

I was attempting to use `choice`  within Schema generation to pick from a list of options but ran into an `UnsupportedField` error. 

It would appear that AbsrtractField returns UnsupportedField wen used with on `Choice` provider.

Example: 
```python
>>> from mimesis.schema import Field, Schema
>>> _ = Field('en')
>>> _('choice', items=[1,2,3])
Traceback (most recent call last):
  File "C:\dev\fakemimesis\.pyenv\lib\site-packages\mimesis\schema.py", line 100, in __call__
    result = self._table[name](**kwargs)
KeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    _('choice', items=[1,2,3])
  File "C:\dev\fakemimesis\.pyenv\lib\site-packages\mimesis\schema.py", line 105, in __call__
    raise UnsupportedField(name)
mimesis.exceptions.UnsupportedField: Field «choice» is not supported.
>>> 
```

## System information

Python version: 3.6.5
Mimesis version: 3.0.0
OS: Windows 10

**Comment by lk-geimfari** [comment]
Seems that is a bug. Field and Schema use Generic which has an attribute `choice`, so it must work.

**Comment by lk-geimfari** [comment]
It happens because of implementation of `Choice` provider. We need to think about how to fix it.

**Comment by lk-geimfari** [comment]
@cryocaustik Here is a dirty workaround if you really need it: 

```python
from mimesis.schema import Field, Schema
from mimesis.providers import Choice

class Choice(Choice):
    def choice(self, *args, **kwargs):
        return self.__call__(*args, **kwargs)


_ = Field('en', providers=(Choice,))

_('choice', items=[1, 3, 4])
```

**Comment by lk-geimfari** [comment]
I would like to fix that bug and create a new release, but I'm really extremely busy, so I hope that I can fix it on weekends.

**Comment by lk-geimfari** [comment]
It's done. 3.1.0 has been released. Thanks for the bug report!
