### ISSUE TITLE
Memory Error creating 1.000.000 records file

### ISSUE THREAD

**Issue by juanzapataadl** [lk-geimfari/mimesis#703]
# Bug report

## What's wrong

First traceback:

Traceback (most recent call last):
  File "multi1.py", line 43, in <module>
    mp_handler()
  File "multi1.py", line 37, in mp_handler
    line = generateCustomerData()
  File "multi1.py", line 15, in generateCustomerData
    personMimesisGenerator = Person('es')
  File "C:\ProgramData\Anaconda3\lib\site-packages\mimesis\providers\person.py", line 38, in __init__
    self.pull(self._datafile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mimesis\providers\base.py", line 150, in pull
    data = get_data(master_locale)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mimesis\providers\base.py", line 145, in get_data
    return json.load(f)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\ProgramData\Anaconda3\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

Second traceback:

Traceback (most recent call last):
  File "multi1.py", line 43, in <module>
    mp_handler()
  File "multi1.py", line 37, in mp_handler
    line = generateCustomerData()
  File "multi1.py", line 15, in generateCustomerData
    personMimesisGenerator = Person('es')
  File "C:\ProgramData\Anaconda3\lib\site-packages\mimesis\providers\person.py", line 38, in __init__
    self.pull(self._datafile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mimesis\providers\base.py", line 150, in pull
    data = get_data(master_locale)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mimesis\providers\base.py", line 144, in get_data
    with open(file_path, 'r', encoding='utf8') as f:
OSError: [Errno 22] Invalid argument: 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\mimesis\\data\\es\\person.json'

## How is that should be

It should create the data without memory errors

## System information

I am using python 3.6 on windows 10 core i7 7th gen (4 cores)

**Comment by juanzapataadl** [comment]
The script has a function and inside it the mimesis generator object was created. It needs to be outside in order to avoid unneccesary calls to create many instances of this objects.
